backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: blog
    label: Blog Posts
    folder: _posts
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}
  - name: faq
    label: FAQ
    folder: _faq
    create: true
    fields:
      - {label: Question, name: title, widget: string}
      - {label: Answer, name: answer, widget: text}
  - name: testimonials
    label: Testimonials
    folder: _testimonials
    create: true
    fields:
      - {label: Name, name: title, widget: string}
      - {label: Text, name: text, widget: text}
